### ISSUE TITLE
Sitemap url

### ISSUE THREAD

**Issue by igdr** [kbond/ZenstruckCacheBundle#8]
Hi, 
Could you add possibility to add full url to the sitemap like:
zenstruck_cache:
    sitemap_provider:
        hosts:
            - http://www.example.com/en/sitemap.xml
            - http://www.example.com/ua/sitemap.xml

This possibility would help to add multi-language sitemaps.
Thanks in advance.

**Comment by kbond** [comment]
Good call, I will look into this.

**Comment by kbond** [comment]
@igdr I just tried this and didn't have a problem. Are you getting some kind of error?

**Comment by igdr** [comment]
The reason is I have structured sitemap.xml (http://www.example.com/en/sitemap.xml) like:

<sitemapindex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/siteindex.xsd">
`<sitemap>`
`<loc>http://www.example.com/en/sitemap.catalog.xml</loc>`
`<lastmod>2015-11-18T21:34:46+02:00</lastmod>`
`</sitemap>`
`<sitemap>`
`<loc>http://www.example.com/en/sitemap.default.xml</loc>`
`<lastmod>2015-11-18T21:35:22+02:00</lastmod>`
`</sitemap>`
`<sitemap>`
`<loc>http://www.example.com/en/sitemap.static.xml</loc>`
`<lastmod>2015-11-18T21:35:22+02:00</lastmod>`
`</sitemap>`
`</sitemapindex>`

Sitemap provider can read only sitemap_index.xml with sub-sitemaps. I think the better way is to read sitemap recursively: if there is sitemap section with loc - read and add urls to crawler.

**Comment by kbond** [comment]
Can't you just create a http://www.example.com/en/sitemap_index.xml ?

I don't want to accommodate something that isn't in the [xsd](http://www.sitemaps.org/schemas/sitemap/0.9/) or [protocol spec](http://www.sitemaps.org/protocol.html).

**Comment by igdr** [comment]
I use PrestaSitemapBundle (https://github.com/prestaconcept/PrestaSitemapBundle). My sitemap is generated automatically via url.

**Comment by kbond** [comment]
Ok, so the `sitemap.xml` in your case is the sitemap index?

**Comment by igdr** [comment]
yes

**Comment by kbond** [comment]
Ok, I will allow the hosts to be either sitemap indexes or sitemaps themselves:

```yaml
zenstruck_cache:
    sitemap_provider:
        hosts:
            - http://example.com # looks for http://example.com/sitemap_index.xml or http://example.com/sitemap.xml
            - http://example.com/en # looks for http://example.com/en/sitemap_index.xml or http://example.com/en/sitemap.xml
            - http://example.com/sitemap.xml # detects if sitemap or sitemap index and act accordingly
            - http://example.com/en/sitemap.xml # same as above
```
